# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.reactive.url=postgresql://localhost:5432/quarkus_db
quarkus.application.name=kafka-listeners

# ========================================
# Micrometer/Prometheus Configuration (for local metrics)
# ========================================
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

# Enable JVM metrics
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
quarkus.micrometer.binder.http-client.enabled=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.virtual-threads.enabled=true
quarkus.micrometer.binder.enable-all=true
quakus.micrometer.export.otlp.url=http://localhost:4318/v1/metrics
#%dev.quakus.micrometer.export.otlp.url=http://localhost:5318/v1/metrics
quarkus.micrometer.binder.kafka.enabled=true
quarkus.micrometer.binder.messaging.enabled=true

# ========================================
# Health Check Configuration
# ========================================
quarkus.smallrye-health.root-path=/q/health


# OTEL Configuration
quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.traces.protocol=http/protobuf
#quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:5318
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4318
#%dev.quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:5318
quarkus.micrometer.export.otlp.url=http://localhost:4318/v1/metrics
#%dev.quarkus.micrometer.export.otlp.url=http://localhost:5318/v1/metrics

# LGTM DevServices ports
#quarkus.observability.lgtm.grafana-port=3001
#quarkus.observability.lgtm.otel-grpc-port=5317
#quarkus.observability.lgtm.otel-http-port=5318
quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{2.}] (%t) %s%e%n
